version: '3.8'

services:
  db:
    image: postgres:13
    container_name: db
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sitekamil_network


  backend:
    build:
      context: ./Uro
    container_name: backend
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    env_file: .env
    depends_on:
      - db
    networks:
      - sitekamil_network

  gateway:
    build:
      context: ./gateway
    container_name: gateway
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:80"
    depends_on:
      - backend
    networks:
      - sitekamil_network

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  sitekamil_network:
